### ISSUE TITLE
script to get and execute a remote python project

### ISSUE THREAD

**Issue by sonnix-de** [sonnix-de/computerspende#1]
A small bash script should check, it the installed version is the current version is and install it on the distribution iso.

**Comment by realwuffi** [comment]
ich würde das gar nicht so kompliziert machen:
eigentlich können wir jedem Team-Mitglied ein sh script geben, welches entweder per wget die aktuellen scripten holt und ausführt oder per git clone sich den inhalt zieht, oder?

**Comment by sonnix-de** [comment]
ich denke wget ist das einfachste - git ist auf den isos noch nicht oben.

**Comment by dmuiX** [comment]
Ich habe jetzt mal eine Version erstellt die erst git und pip installiert, dann über git clone das aktuelle script bzw. alle Dateien aus dem repo herunterlädt, dann das script ausführt und am Ende wieder alles löscht. Das lade ich jetzt geich mal hoch und teste ich jetzt dann nochmal auf einem der neuen Fujitsu Notebooks. Zudem habe ich eine Funktion eingebaut die zu Beginn eine config.json Datei erstellt, das hat nämlich noch gefehlt.

**Comment by dmuiX** [comment]
Das Script funktioniert jetzt. Ist aber nervig, wenn man jedes mal den Token eintippen muss. Ergo wäre es wohl sinnvoll entweder das ganze Script oder aber zumindest die setup.sh und config.json auf nem USB Stick zu speichern
