### ISSUE TITLE
"Free text" should be on top of description

### ISSUE THREAD

**Issue by realwuffi** [sonnix-de/computerspende#15]
I think we should set the text, that you can enter during the creation of the issue to the top of the issue

example:

this is the text I entered in the python script

Auflösung: ....
Grafikkarte: .....
USB3: ja

**Comment by dmuiX** [comment]
why remove graphicscard? could be interesting when its a gaming card :D. And we can leave it there at the end of the description.
The rest makes sense.

**Comment by realwuffi** [comment]
okay, then we leave it in.
I extracted the screen resolution to an extra issue with other ones to follow

**Comment by dmuiX** [comment]
Regarding these issues. Have already a code ready but haven't uploaded it. Will do that this week.

**Comment by dmuiX** [comment]
@ the moment it is at the end. And to me it looks great that way, so I would leave it like that. But see for yourself.
