### ISSUE TITLE
Add screen resolution to description

### ISSUE THREAD

**Issue by realwuffi** [sonnix-de/computerspende#17]
Th resolution of the screen should be added to the description,
e. g. 
Auflösung: 1280x1014

**Comment by antonstech** [comment]
Bin dabei

**Comment by antonstech** [comment]
Hab's schon fertig gemacht, Pull kommt dann die nächsten Tage

**Comment by antonstech** [comment]
#20 Pull ist draußen

**Comment by antonstech** [comment]
#21 Mittlerweile

**Comment by antonstech** [comment]
So Pulls sind weg aber ich kann hier jetzt direkt hochladen; https://github.com/sonnix-de/computerspende/commit/4045a0771b37005f80a46329dbbcc8c633f26efc
