### ISSUE TITLE
Add CD/DVD drive to the description

### ISSUE THREAD

**Issue by realwuffi** [sonnix-de/computerspende#19]
Add availability of CD/DVD drive to the description

**Comment by dmuiX** [comment]
Okay will add that

**Comment by antonstech** [comment]
Also ich habe das ganze jetzt schon gemacht, pull kommt bald

**Comment by antonstech** [comment]
Habs mit https://github.com/sonnix-de/computerspende/commit/4045a0771b37005f80a46329dbbcc8c633f26efc gemacht
