### ISSUE TITLE
Detection of cd-rom breaks whole script

### ISSUE THREAD

**Issue by realwuffi** [sonnix-de/computerspende#22]
Major bug: script fails at detection of cd-rom

checkforcd = subprocess.check_output("sudo --.-.lshw -C disk",shell=True).decode()

The --.-. seems strange

Also it would be way better no just to have "Ja / Nein", but to have a bit more details like if it is able to write DVDs etc.
So if you would call "sudo lshw -json -C disk" and try to extract the node from "id" : "cdrom"
Then you could append all the "capabilities" like that: cd-r cd-rw dvd dvd-ram

This ist the output from my notebook:
```
  {
    "id" : "cdrom",
    "class" : "disk",
    "claimed" : true,
    "handle" : "SCSI:02:00:00:00",
    "description" : "DVD-RAM writer",
    "product" : "DVDRAM GT80N",
    "vendor" : "HL-DT-ST",
    "physid" : "0.0.0",
    "businfo" : "scsi@2:0.0.0",
    "logicalname" : ["/dev/cdrom", "/dev/cdrw", "/dev/dvd", "/dev/dvdrw", "/dev/sr0"],
    "dev" : "11:0",
    "version" : "FS05",
    "configuration" : {
      "ansiversion" : "5",
      "status" : "nodisc"
    },
    "capabilities" : {
      "removable" : "support is removable",
      "audio" : "Audio CD playback",
      "cd-r" : "CD-R burning",
      "cd-rw" : "CD-RW burning",
      "dvd" : "DVD playback",
      "dvd-r" : "DVD-R burning",
      "dvd-ram" : "DVD-RAM burning"
    }
  }
```

**Comment by dmuiX** [comment]
I have put your improvement to another issue. as it is easy to remove the bug, but might take some time to create your improvment ;)
