### ISSUE TITLE
ImportError: No module named psutil on ubuntu2004

### ISSUE THREAD

**Issue by dmuiX** [sonnix-de/computerspende#3]
I get this error if I try to run python3 main.py

**Comment by sonnix-de** [comment]
wird eventuell nicht mehr gebraucht.
der befehl lshw bringt schon ziemlich viel infos.
ansonsten: pip3 install psutil

**Comment by dmuiX** [comment]
jo genau, das wollte ich zur setup.sh hinzufügen.

**Comment by realwuffi** [comment]
Wurde in die requirements mit aufgneommen
