### ISSUE TITLE
ModuleNotFoundError: No module named 'consolemenu' on ubuntu 20.04

### ISSUE THREAD

**Issue by dmuiX** [sonnix-de/computerspende#4]
I get this error if I run python main.py:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from consolemenu import *
ModuleNotFoundError: No module named 'consolemenu'

**Comment by sonnix-de** [comment]
in der setup.sh datei ist der Installationsbefehl

**Comment by dmuiX** [comment]
der Befehl passt nur nicht. Fix folgt sobald ich ne Push Berechtigung habe ;).

**Comment by dmuiX** [comment]
hat sich erledigt da die requirements jetzt enthalten sind
