### ISSUE TITLE
Einheitliche ganzzahlige Darstellung des RAMs in Mantis

### ISSUE THREAD

**Issue by dmuiX** [sonnix-de/computerspende#9]
Ich denke es wäre sinnvoll den RAM in Mantis ganzzahlig darzustellen. Ergo 4 oder 8 oder 16 GB.

**Comment by realwuffi** [comment]
Dachte ich auch erst, aber ich finde es ganz okay so: denn so soeht man den effektiv nutzbaren und kann auch auf den Speicher zurückschließen, der von der Grafikkarte beansprucht wird.

Aber ich kann mit beiden Werten leben.

**Comment by dmuiX** [comment]
Okay. Wegen mir können wir das auch so lassen. Dann schließ ich das Issue mal wieder
